### ISSUE TITLE
error with resources and pages in multitenant

### ISSUE THREAD

**Issue by zxstudio-llc** [andrewdwallo/filament-companies#142]
@andrewdwallo  Currently I am presenting an error with the tenancy part, when installing I am requiring that the pages and resources be reflected in the company module and from there manage the roles, permissions and authorizations part but when using php artisan make : filament-page or php artisan make:filament-resource allows me to choose the creation route (admin or company) when choosing company it reflects the module in the panel but when I enter it I get that the route **"Route [filament.admin. tenant .profile] not defined. "**, the same thing happens when installing the filament-shield plugin, which is what I use to handle the authorization issue.

**Comment by andrewdwallo** [comment]
You have to register the Profile page in the Admin panel as you mentioned in another issue.

**Comment by zxhub-llc** [comment]
Of course I understand it perfectly, the objective as such is to be able to implement all the modules from the administrative panel so that an administrator can review the information and have access to the entire company and in the user panel access to certain panels is defined according to the role of the user, for example, a user who manages accounting will only have access to invoices and the stock of the product and the sales user will only be able to access the consumption of the products without being able to create new products or increase the stock, so far I have tried in a personal repository but with the implementation of the filament shield plugin which gives me this type of permissions when adding new resources or pages to the company panel it gives me this error mentioned before but in the user panel it does not, additionally is there a way to implement filament shield without me present this error when entering the roles and permissions resource?

**Comment by andrewdwallo** [comment]
Well maybe this is a Filament shield error and not an error with this package?

**Comment by zxhub-llc** [comment]
So I understand a question when publishing the roles resource in this package, is it possible from there to manage all the permissions and roles or is there not included a role and permissions package?

**Comment by andrewdwallo** [comment]
The roles and permissions of this package are not the same as Filament shield, but similar. Look up Laravel policies.

**Comment by zxhub-llc** [comment]
perfect thanks for the clarification I will review the documentation

**Comment by andrewdwallo** [comment]
@zxstudio-llc Has your issue been resolved?

**Comment by zxhub-llc** [comment]
In fact, I have managed to solve it, currently I only work with a view that is the one that the plugin generates, I have not presented any new features, in addition I am using a test model that you have erpsaas that I have been able to modify to my liking. Currently I am implementing a resource of shop to load products
