### ISSUE TITLE
URL containing company slug rather than ID

### ISSUE THREAD

**Issue by Jamesking56** [andrewdwallo/filament-companies#143]
Hi,

Feature request, would be nice if the URL was the company name (slugged) rather than the ID:

`/1/profile` -> `/acme-corp/profile`

Using the ID way reveals to the user how many companies exist, which isn't the greatest.

**Comment by andrewdwallo** [comment]
This is not an issue with this package, please make a discussion for feature request. Also, this feature is available through Filament by default... See [here](https://filamentphp.com/docs/3.x/panels/tenancy#configuring-the-slug-attribute).

You can just do this, for example:
```php
->tenant(Company::class, 'name')
```

If the current company name was "acme-corp", the url will display "/acme-corp/profile" as an example instead of the current company id.

Closing this issue.
